---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd
  namespace: {{ .Values.nfd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  name: nfd
  source: operators413
  sourceNamespace: openshift-marketplace
  channel: stable
  installPlanApproval: Automatic
